import path from 'node:path';
import { promises as fs } from 'node:fs';
import { createHash } from 'node:crypto';
import type { MaterializeResult, ProviderContext, SecretsPullResult } from '../types.js';
import { ensureDir, ensureGitignored } from '../../util/fs.js';
import { loadState, patchState, type SecretsBase } from '../../state.js';

const sha256 = (s: string): string => createHash('sha256').update(s).digest('hex');

/**
 * Hash a secret set so we can tell later whether it changed, and *which keys*
 * changed, without ever writing a plaintext value to `WorkspaceState` (which
 * lives in the state dir, not the repo, but is still not a secret store).
 */
export function hashSecrets(values: Record<string, string>): Omit<SecretsBase, 'pulledAt'> {
  const keys = Object.keys(values).sort();
  const keyHashes: Record<string, string> = {};
  for (const k of keys) keyHashes[k] = sha256(values[k]!);
  return { hash: sha256(keys.map((k) => `${k}=${keyHashes[k]}`).join('\n')), keyHashes };
}

/** Escape a value for a double-quoted dotenv assignment. */
export function dotenvEscape(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\$/g, '\\$')
    .replace(/`/g, '\\`');
}

export function renderDotenv(values: Record<string, string>): string {
  const header =
    '# Generated by envbeam — DO NOT COMMIT. Secrets are pulled from your provider.\n';
  const lines = Object.entries(values).map(([k, v]) => `${k}="${dotenvEscape(v)}"`);
  return header + lines.join('\n') + (lines.length ? '\n' : '');
}

function renderRunEnv(values: Record<string, string>): string {
  const lines = Object.entries(values).map(([k, v]) => `export ${k}="${dotenvEscape(v)}"`);
  return '#!/usr/bin/env sh\n# Generated by envbeam — source this to load secrets.\n' + lines.join('\n') + '\n';
}

/**
 * Which keys differ between the file on disk and what we are about to write.
 * Only key NAMES are ever surfaced — a value must not reach a log or a prompt.
 */
function changedKeyNames(existing: string, next: Record<string, string>): string[] {
  const before = parseDotenv(existing);
  const names = new Set([...Object.keys(before), ...Object.keys(next)]);
  return [...names].filter((k) => before[k] !== next[k]).sort();
}

/**
 * Guard an overwrite of a file the user may have hand-edited (SYNC_SAFETY.md S2).
 * Reports whether to write, and where the pre-overwrite copy was saved.
 *
 * `dotenvHash` is the hash of the bytes envbeam itself last wrote. A file that
 * still matches it has no local edits and is overwritten silently, as before.
 * A file that differs is backed up first, always — the values in it may exist
 * nowhere else.
 */
async function guardLocalEdits(
  ctx: ProviderContext,
  file: string,
  rel: string,
  nextValues: Record<string, string>,
): Promise<{ write: boolean; backupPath?: string }> {
  const state = await loadState(ctx.workspaceRoot);
  let existing: string;
  try {
    existing = await fs.readFile(file, 'utf8');
  } catch {
    return { write: true }; // nothing there to lose
  }
  // No recorded hash (first pull on this machine, or pre-0.19 state) or an
  // untouched file: nothing to protect.
  if (!state.dotenvHash || sha256(existing) === state.dotenvHash) return { write: true };

  const changed = changedKeyNames(existing, nextValues);
  const backupRel = `${rel}.envbeam-backup`;
  await fs.writeFile(path.join(ctx.workspaceRoot, backupRel), existing, { mode: 0o600 });
  await ensureGitignored(ctx.workspaceRoot, backupRel);

  ctx.logger.warn(`${rel} has local edits that envbeam did not write.`);
  if (changed.length) ctx.logger.sub(`  differing key(s): ${changed.join(', ')}`);
  ctx.logger.sub(`  saved a copy to ${backupRel}`);

  if (ctx.force || !ctx.prompter.interactive) {
    // `--yes` keeps the historical overwrite behavior; the backup is the safety net.
    return { write: true, backupPath: backupRel };
  }
  const overwrite = await ctx.prompter.confirm(`Overwrite ${rel} with the values from the provider?`, true);
  return { write: overwrite, backupPath: backupRel };
}

/**
 * Materialize pulled secrets into the runtime mechanism (PRD §7.3). Never
 * writes anything git-tracked: the output path is gitignored.
 */
export async function materializeSecrets(
  ctx: ProviderContext,
  pulled: SecretsPullResult,
): Promise<MaterializeResult> {
  const cfg = ctx.config.secrets;
  const mode = cfg?.output ?? 'dotenv';

  const rel = mode === 'run-wrapper' ? path.join('.envbeam', 'runenv.sh') : cfg?.dotenvPath ?? '.env';
  const file = path.join(ctx.workspaceRoot, rel);
  const content = mode === 'run-wrapper' ? renderRunEnv(pulled.values) : renderDotenv(pulled.values);

  if (ctx.dryRun) return { mode, path: rel, count: pulled.count };

  const guard = await guardLocalEdits(ctx, file, rel, pulled.values);
  if (!guard.write) {
    ctx.logger.sub(`kept your ${rel}; the provider's values were not written`);
    return { mode, path: rel, count: pulled.count, backupPath: guard.backupPath, skipped: 'local edits kept' };
  }

  await ensureDir(path.dirname(file));
  await fs.writeFile(file, content, { mode: 0o600 });
  await ensureGitignored(ctx.workspaceRoot, mode === 'run-wrapper' ? '.envbeam/' : rel);

  // Record the base: what the provider held, and the exact bytes we wrote. A
  // later pull compares the file on disk against `dotenvHash` to tell a local
  // edit apart from "unchanged since we generated it", and a two-way push uses
  // `secretsBase` to attribute each changed key to a side.
  await patchState(ctx.workspaceRoot, {
    secretsBase: { ...hashSecrets(pulled.values), pulledAt: new Date().toISOString() },
    dotenvHash: sha256(content),
  });

  return { mode, path: rel, count: pulled.count, backupPath: guard.backupPath };
}

/** Parse a dotenv file's KEY=value pairs (handles quotes + `export`). */
export function parseDotenv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.replace(/^export\s+/, '').match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!m) continue;
    const key = m[1]!;
    let val = m[2]!;
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      const quote = val[0];
      val = val.slice(1, -1);
      if (quote === '"') {
        val = val
          .replace(/\\n/g, '\n')
          .replace(/\\r/g, '\r')
          .replace(/\\"/g, '"')
          .replace(/\\\$/g, '$')
          .replace(/\\`/g, '`')
          .replace(/\\\\/g, '\\');
      }
    }
    out[key] = val;
  }
  return out;
}

/** Read names + count from an existing materialized dotenv (for status). */
export async function readMaterialized(ctx: ProviderContext): Promise<{ present: boolean; count: number }> {
  const cfg = ctx.config.secrets;
  const rel = cfg?.output === 'run-wrapper' ? '.envbeam/runenv.sh' : cfg?.dotenvPath ?? '.env';
  const file = path.join(ctx.workspaceRoot, rel);
  try {
    const text = await fs.readFile(file, 'utf8');
    const count = text
      .split(/\r?\n/)
      .filter((l) => /^(export\s+)?[A-Za-z_][A-Za-z0-9_]*=/.test(l.trim())).length;
    return { present: true, count };
  } catch {
    return { present: false, count: 0 };
  }
}
