import path from 'node:path';
import { promises as fs } from 'node:fs';
import type { MaterializeResult, ProviderContext, SecretsPullResult } from '../types.js';
import { ensureDir, ensureGitignored } from '../../util/fs.js';

/** Escape a value for a double-quoted dotenv assignment. */
export function dotenvEscape(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\$/g, '\\$')
    .replace(/`/g, '\\`');
}

export function renderDotenv(values: Record<string, string>): string {
  const header =
    '# Generated by envbeam — DO NOT COMMIT. Secrets are pulled from your provider.\n';
  const lines = Object.entries(values).map(([k, v]) => `${k}="${dotenvEscape(v)}"`);
  return header + lines.join('\n') + (lines.length ? '\n' : '');
}

function renderRunEnv(values: Record<string, string>): string {
  const lines = Object.entries(values).map(([k, v]) => `export ${k}="${dotenvEscape(v)}"`);
  return '#!/usr/bin/env sh\n# Generated by envbeam — source this to load secrets.\n' + lines.join('\n') + '\n';
}

/**
 * Materialize pulled secrets into the runtime mechanism (PRD §7.3). Never
 * writes anything git-tracked: the output path is gitignored.
 */
export async function materializeSecrets(
  ctx: ProviderContext,
  pulled: SecretsPullResult,
): Promise<MaterializeResult> {
  const cfg = ctx.config.secrets;
  const mode = cfg?.output ?? 'dotenv';

  if (mode === 'run-wrapper') {
    const dir = path.join(ctx.workspaceRoot, '.envbeam');
    const file = path.join(dir, 'runenv.sh');
    if (!ctx.dryRun) {
      await ensureDir(dir);
      await fs.writeFile(file, renderRunEnv(pulled.values), { mode: 0o600 });
      await ensureGitignored(ctx.workspaceRoot, '.envbeam/');
    }
    return { mode, path: path.relative(ctx.workspaceRoot, file), count: pulled.count };
  }

  const rel = cfg?.dotenvPath ?? '.env';
  const file = path.join(ctx.workspaceRoot, rel);
  if (!ctx.dryRun) {
    await ensureDir(path.dirname(file));
    await fs.writeFile(file, renderDotenv(pulled.values), { mode: 0o600 });
    await ensureGitignored(ctx.workspaceRoot, rel);
  }
  return { mode, path: rel, count: pulled.count };
}

/** Parse a dotenv file's KEY=value pairs (handles quotes + `export`). */
export function parseDotenv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.replace(/^export\s+/, '').match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!m) continue;
    const key = m[1]!;
    let val = m[2]!;
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      const quote = val[0];
      val = val.slice(1, -1);
      if (quote === '"') {
        val = val
          .replace(/\\n/g, '\n')
          .replace(/\\r/g, '\r')
          .replace(/\\"/g, '"')
          .replace(/\\\$/g, '$')
          .replace(/\\`/g, '`')
          .replace(/\\\\/g, '\\');
      }
    }
    out[key] = val;
  }
  return out;
}

/** Read names + count from an existing materialized dotenv (for status). */
export async function readMaterialized(ctx: ProviderContext): Promise<{ present: boolean; count: number }> {
  const cfg = ctx.config.secrets;
  const rel = cfg?.output === 'run-wrapper' ? '.envbeam/runenv.sh' : cfg?.dotenvPath ?? '.env';
  const file = path.join(ctx.workspaceRoot, rel);
  try {
    const text = await fs.readFile(file, 'utf8');
    const count = text
      .split(/\r?\n/)
      .filter((l) => /^(export\s+)?[A-Za-z_][A-Za-z0-9_]*=/.test(l.trim())).length;
    return { present: true, count };
  } catch {
    return { present: false, count: 0 };
  }
}
