/** Human-readable docs for each config field (PRD §9a `config explain`). */
export const FIELD_DOCS: Record<string, string> = {
  version: 'Config schema version. Always 1.',
  workspace: 'Human-readable workspace name; also used to tag DB snapshots.',
  'git.identity': 'Named identity (e.g. github:work) resolving the SSH host alias / account to use.',
  'git.remote': 'Git remote name (default origin).',
  'git.branch': 'Branch to track, or "current" to follow the checked-out branch.',
  'git.autopush': 'When true, pause pushes the branch.',
  'git.autopull': 'resume pull policy: ff-only fast-forwards a clean tree; off skips.',
  'secrets.provider': 'Secrets plugin name (doppler | onepassword | third-party).',
  'secrets.identity': 'Named identity selecting which secrets account to use.',
  'secrets.project': 'Provider project reference (Doppler project). No secret values.',
  'secrets.config': 'Provider config/environment (Doppler config, e.g. dev).',
  'secrets.vault': '1Password vault name.',
  'secrets.item': '1Password item whose fields are the env vars (label=KEY).',
  'secrets.output': 'How secrets are materialized: dotenv (gitignored .env) or run-wrapper.',
  'secrets.dotenvPath': 'Path for the gitignored dotenv file (default .env).',
  'container.mode': 'Container orchestration: devcontainer | compose | none.',
  'container.composeFile': 'Path to the docker-compose file (compose mode).',
  'container.service': 'Primary compose service to bring up.',
  'container.upOnResume': 'Bring the container up during resume (default true).',
  'container.stopOnPause': 'Stop the container during pause (default false — leave running).',
  'database.provider': 'Database plugin: postgres | mysql. Auto-detected from compose.',
  'database.mode': 'migrations-only (fast, default) | snapshot (carry data).',
  'database.restore': 'On resume, handle a newer snapshot: prompt | auto | off.',
  'database.connection': '"from-secrets" resolves host/creds from loaded secrets, or a URL / env-var name.',
  'database.service': 'Container service to dump/restore against.',
  'database.migrate': 'Apply pending migrations on resume (both modes).',
  'database.migrateCommand': 'Stack-specific migrate command; auto-detected per stack.',
  'database.changeTables': 'Tables watched for change-detection (defaults to snapshot include set).',
  'database.snapshot.dataOnly': 'Dump data only; schema comes from migrations.',
  'database.snapshot.compress': 'Compress the dump.',
  'database.snapshot.tables.include': 'Limit the dump to these tables (patterns allowed).',
  'database.snapshot.tables.exclude': 'Exclude these tables from the dump.',
  'database.snapshot.changeDetection': 'Only auto-prompt a snapshot when watched tables changed.',
  'database.sync.target': 'Where snapshots live: syncthing | s3 | local-folder.',
  'database.sync.identity': 'Account for the sync target (e.g. s3:personal).',
  'database.sync.path': 'Folder path for syncthing/local-folder targets.',
  'database.sync.bucket': 'S3 bucket name.',
  'database.sync.prefix': 'Key/path prefix within the bucket or folder.',
  'database.sync.region': 'S3 region.',
  'database.sync.encrypt': 'At-rest encryption of snapshots (required): age (default) | gpg.',
  'database.sync.recipient': 'age/gpg recipient (public key / key id) when encrypting.',
  'database.sync.maxSizeMB': 'Warn/abort when a dump exceeds this size.',
  'database.sync.keep': 'Retain the N most recent snapshots.',
  'session.provider': 'Session sync: claude-native (built-in, default) | claude-sync | remote-control | none.',
  'session.scope': 'sessions (just session history) | full.',
  'session.remotePath': 'Remote project path mapping for cross-machine path translation.',
};

export function explainField(field: string): string | undefined {
  return FIELD_DOCS[field];
}
